version: "3.8"

services:
  mongodb:
    image: mongo:5.0.15
    container_name: ysoul_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27019:27017"
    volumes:
      - ysoul_mongo_data:/data/db

  postgres:
    image: postgres:15
    container_name: ysoul_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - ysoul_postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: ysoul_backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev

volumes:
  ysoul_mongo_data:
  ysoul_postgres_data:
